services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@wMap123!"
    ports:
      - "1434:1433"
    volumes:
      - pawmap-sqlserver-data:/var/opt/mssql

volumes:
  pawmap-sqlserver-data:
